languageCode: "en-us"
baseUrl: "https://tempetechie.net"
title: "Tempe Techie's blog"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

params:
  author: "Tempe Techie"
  style: "dark"
  copyCodeButton: true # true by default
  facebook_admin: "" # Facebook Admin ID for OpenGraph (optional)
  social:
  - id: github
    name: tempe-techie
  - id: farcaster
    name: tempetechie.eth
  images:
    - cover.jpg # relative path to "static" directory

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
